#!/usr/bin/env python3
"""Regenerate the README's version table and image size from versions.env.

Run by the build workflow after a successful push so the README always describes
the image that is actually published, rather than whatever was true when someone
last edited it by hand.
"""
import os
import re
import sys

START = "<!-- BEGIN GENERATED -->"
END = "<!-- END GENERATED -->"

TOOLS = [
    ("RUNNER_VERSION", "actions/runner", "tarball"),
    ("GO_VERSION", "Go", "tarball"),
    ("NODE_VERSION", "Node", "tarball"),
    ("TERRAFORM_VERSION", "Terraform", "release zip"),
    ("OPENTOFU_VERSION", "OpenTofu", "release zip"),
    ("OPENBAO_VERSION", "OpenBao", "release tarball"),
    ("ASDF_VERSION", "asdf", "release tarball"),
    ("GOLANGCI_LINT_VERSION", "golangci-lint", "asdf"),
    ("ACTIONLINT_VERSION", "actionlint", "asdf"),
    ("GORELEASER_VERSION", "goreleaser", "asdf"),
    ("TRIVY_VERSION", "trivy", "asdf"),
    ("HADOLINT_VERSION", "hadolint", "asdf"),
    ("YAMLLINT_VERSION", "yamllint", "asdf"),
    ("GOSEC_VERSION", "gosec", "go install"),
    ("GOVULNCHECK_VERSION", "govulncheck", "go install"),
    ("MARKDOWNLINT_VERSION", "markdownlint-cli", "npm"),
    ("OPENSPEC_VERSION", "@fission-ai/openspec", "npm"),
]


def read_versions(path="versions.env"):
    out = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def main():
    size = os.environ.get("IMAGE_SIZE", "").strip()
    digest = os.environ.get("IMAGE_DIGEST", "").strip()
    versions = read_versions()

    rows = ["| Tool | Version | Installed via |", "|---|---|---|"]
    for key, name, how in TOOLS:
        if key in versions:
            rows.append("| {} | {} | {} |".format(name, versions[key], how))

    missing = [k for k, _, _ in TOOLS if k not in versions]
    extra = [k for k in versions if k not in {t[0] for t in TOOLS}]
    if missing:
        print("versions.env is missing: {}".format(", ".join(missing)), file=sys.stderr)
    if extra:
        print("not rendered (add to TOOLS): {}".format(", ".join(extra)), file=sys.stderr)

    block = [
        START,
        "",
        "<!-- Generated by .github/workflows/build.yml. Edits here are overwritten. -->",
        "",
    ]
    if size:
        block += ["**Compressed size:** {} (what each node downloads)".format(size), ""]
    if digest:
        block += ["**Current digest:** `{}`".format(digest), ""]
    block += rows + ["", END]

    readme = open("README.md").read()
    if START not in readme or END not in readme:
        print("no generated block markers in README.md", file=sys.stderr)
        return 1

    readme = re.sub(
        re.escape(START) + r".*?" + re.escape(END), "\n".join(block), readme, flags=re.S
    )
    open("README.md", "w").write(readme)
    print("README updated: {} tools, size={}".format(len(rows) - 2, size or "unknown"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
